#ifndef AKS_PROJECT_CONFIG_HPP
#define AKS_PROJECT_CONFIG_HPP

#define INT_BITS 10
#define DOUBLE_BITS 20
#define VARIABLES 2

#define POPULATION_SIZE 1000
#define GENERATIONS 500
#define MAX_NUM 512
#define MIN_NUM -512
#define MUTATION_CHANCE 0.1
#define THREADS 4

#endif //AKS_PROJECT_CONFIG_HPP
